services:
  postgres:
    image: postgres:16-alpine
    container_name: ac-commerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: accommerce
      POSTGRES_PASSWORD: accommerce
      POSTGRES_DB: accommerce
    ports:
      - "5432:5432"
    volumes:
      - ac_commerce_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accommerce -d accommerce"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: ac-commerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ac-commerce-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  ac_commerce_pg:
